name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Set up environment variables
      run: |
        echo "FIREBASE_API_KEY_ANDROID=${{ secrets.FIREBASE_API_KEY_ANDROID }}" >> $GITHUB_ENV
        echo "FIREBASE_APP_ID_ANDROID=${{ secrets.FIREBASE_APP_ID_ANDROID }}" >> $GITHUB_ENV
        echo "FIREBASE_API_KEY_IOS=${{ secrets.FIREBASE_API_KEY_IOS }}" >> $GITHUB_ENV
        echo "FIREBASE_APP_ID_IOS=${{ secrets.FIREBASE_APP_ID_IOS }}" >> $GITHUB_ENV
        echo "FIREBASE_MESSAGING_SENDER_ID_ANDROID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_ANDROID }}" >> $GITHUB_ENV
        echo "FIREBASE_MESSAGING_SENDER_ID_IOS= ${{ secrets.FIREBASE_MESSAGING_SENDER_ID_IOS }}" >> $GITHUB_ENV
        echo "FIREBASE_API_KEY_LOCATION=${{ secrets.FIREBASE_API_KEY_LOCATION }}" >> $GITHUB_ENV
        echo "FIREBASE_PROJECT_ID_ANDROID=${{ secrets.FIREBASE_PROJECT_ID_ANDROID }}" >> $GITHUB_ENV
        echo "FIREBASE_PROJECT_ID_IOS=${{ secrets.FIREBASE_PROJECT_ID_IOS }}" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Build APK
      run: flutter build apk --release

    - name: Build iOS
      if: runner.os == 'macOS'
      run: flutter build ios --release
